sudo: required
services:
  - docker

before_install:
  - docker build -t novelldev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true novelldev/docker-react npm run test -- --coverage

language: generic
